name = "jq"
description = ""
version = "1.7.1"

[darwin.amd64]
target = "https://github.com/jqlang/jq.git"
commit = "71c2ab509a8628dbbad4bc7b3f98a64aa90d3297"
dev-depends = [
  "libtool",
  "make",
  "automake",
  "autoconf",
  "git"
  ]
depends = []
build = [
  "autoreconf -i",
  "./configure --with-oniguruma=builtin",
  "make -j8",
  "make check",
  "make install"
  ]
